### PR TITLE
factorial.go

### PR DESCRIPTION
**Pull request by egor-geller**
without recursion

### CODE REVIEW

**Review by burov — APPROVED** [review]
Looks good!

**Review by imatsiash-ib — COMMENTED** [review]
Code is not `go fmt`-ed

**Comment by egor-geller** [comment]
@imatsiash-ib  what does it mean not `go fmt` -ed ?
do you mean this : golang.go/cmd/gofmt ?

**Comment by imatsiash-ib** [comment]
@egor-geller please use `go fmt factorial.go` for your file.

**Review by imatsiash-ib — APPROVED** [review]

**Pull request closed without merging**
